### PR TITLE
feat: add authorizeWithCode method

### PR DESCRIPTION
**Pull request by marinacabrera**

### CODE REVIEW

**Comment by ctjlewis** [comment]
I'm having a weird issue where the prompt automatically wraps a newline, and then won't accept any new `\n`s as submissions.

I will end up rewriting a better `prompts` substitute. It was not really high priority but this PR should work on my machine, but the prompts library is breaking.

image

**Comment by ctjlewis** [comment]
I added a test btw and all the other tests are commented out. Run `yarn test`

**Comment by marinacabrera** [comment]
hmm I noticed you removed the "" empty string and `initial` key from the options, maybe that's the problem? It defaults to a newline? Still testing

Do you want me to address it? And thanks for adding tests, anything else you need for this PR?

**Comment by marinacabrera** [comment]
also this one seems to be more frequently updated: https://github.com/flatiron/prompt

**Comment by ctjlewis** [comment]
You’re good to fix it by pushing up directly to this branch if you want, my bad for breaking in refactor

**Comment by marinacabrera** [comment]
Alright will be back in a bit to fix it

**Comment by marinacabrera** [comment]
so seems like I wasn't able to reproduce this bug, added back the `initial: ""`, can you test again? 

tested on integrated terminal on vscode, ssh session on iterm2, codespaces, not sure what's going on.

**Comment by marinacabrera** [comment]
ohhhh! nvm! what a weird thing, now I'm getting this wrapped newline when running `yarn test`. gimme a few minutes

**Comment by marinacabrera** [comment]
@ctjlewis did you try linking this branch to `upg` repo? That's how I "tested", seems like an ava thing, maybe? Only happens on `yarn test` for me. 

Also switching to `prompt` library gives me the same thing.

**Comment by marinacabrera** [comment]
steps to do a functional test with upg (adding `true` to AUTH0_CLIENT.login):

```
@marinacabrera ➜ /workspaces/tools/auth0-node-client (feat/authorize-with-code ✗) $ yarn build
@marinacabrera ➜ /workspaces/tools/auth0-node-client (feat/authorize-with-code ✗) $ yarn link
@marinacabrera ➜ /workspaces/tools/auth0-node-client (feat/authorize-with-code ✗) $ cd ..
@marinacabrera ➜ /workspaces/tools/auth0-node-client (feat/authorize-with-code ✗) $ 
@marinacabrera ➜ /workspaces/tools (feat/login-paste-code ✗) $ yarn link auth0-node-client 
@marinacabrera ➜ /workspaces/tools (feat/login-paste-code ✗) $ yarn build
@marinacabrera ➜ /workspaces/tools (feat/login-paste-code ✗) $ node packages/upg/dist/bin.js login
```

results in: 
image

**Comment by marinacabrera** [comment]
ok seems like this is not possible due to stdin/stdout issues with Ava. It would be sort of like an end-to-end testing in this case (requiring user interaction), so not sure this is the ideal library for it. 

Are you able to run it by linking or using yarn workspaces, instead of going through ava/testing pipelines?

**Comment by marinacabrera** [comment]
https://github.com/marinacabrera/devs-not-needed 

Updated the template using my experimental forks so you can see that is about the testing suite, as it works in normal tty. 

(cant login anymore :()

**Comment by ctjlewis** [comment]
No need to link in UPG, running “yarn test” in this repo will run a quick test. I’ll look into this.

**Comment by ctjlewis** [comment]
I just tested using `tsmodule src/example/index.ts` (where I added `AUTH0_CLIENT.login(true)`) and it does work like you said. Not sure what's up with ava.

**Comment by marinacabrera** [comment]
It's just that it hijacks stdin/stdout, so impossible for a prompt to be captured, it just hangs the tty, is this supposed to be a unit test or integration test? I did some research and couldn't find anything that doesn't explicitly mock the prompt result. 

I can write a unit test that makes sure prompt function is called, and that if code is validated and such. What are your thoughts on this? Let me know how else I can help, this tool is incredible.

**Comment by ctjlewis** [comment]
@marinacabrera OK, I rewrote testing and logging and soon prompts from scratch, though after 2 days of work I found out really we could've just made `await import()` work, and you can see how that's done with the examples in the current testing library also. If you don't want to hide the process behind the spinner, you can just `tsmodule tests/example/login.ts` for instance.

`yarn test` should work reasonably now on your end. Let me know.

**Comment by ctjlewis** [comment]
Also, the flow will be reversed - we'll still open with a browser basically on one side.

You will use `upg authorize -g, --generate` to generate an auth code on a device where you have a browser, then copy it by clicking it in the redirect, and using `upg authorize` on your SSH device, you can paste it in and sign up.

**Comment by ctjlewis** [comment]
This will ship in the morning, but basically on your "normal" device, `upg authorize`, "would you like to generate or enter a code?", you hit generate, lands you eventually on a big screen, click to copy, process closes when you hit the screen.

Other device (SSH), `upg authorize`, I'd like to enter a code, paste, enter, logged in.

**Pull request merged**
